# Use root/example as user/password credentials
version: '3.8'

services:

  fwaProject:
    image: mariadb:11.1.2
    environment:
      MARIADB_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1