# Use root/example as user/password credentials
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.development
    depends_on:
      - fwaProject

  fwaProject:
    image: mariadb:11.1.2
    environment:
      MARIADB_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8085:80
    environment:
      - PMA_ARBITRARY=1
