# Use root/example as user/password credentials
version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.development
    depends_on:
      - fwaProject

  fwaProject:
    container_name: db
    image: mariadb:11.1.2
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 8085:80
    environment:
      - PMA_ARBITRARY=1
